--- #YAML:1.0
name:               Text-MicroMason
version:            2.07
abstract:           Simple and Extensible Templating
author:
    - Alan Ferrency <ferrency@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::MixinFactory:  0.9
    Cwd:                  2.21
    File::Spec:           0.9
    Test::More:           0.48
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
